### ISSUE TITLE
Research about UTD SSO integration

### ISSUE THREAD

**Issue by IanW23** [Alexw360/Virtual-TA#3]

**Comment by IanW23** [comment]
UTD SSO Integration for new applications or services can be done via the Atlas Service Portal. 

https://atlas.utdallas.edu/TDClient/30/Portal/Requests/TicketRequests/NewForm?ID=bwtdq9fXOq4_&RequestorType=ServiceOffering

**Comment by IanW23** [comment]
Items needed: 

Application Name
Details of Application and Request
Will former employees require access to application?
Will retirees require access to application?
MFA (DUO) Enabled?
Application Entity ID (This is a unique identifier for your application, which is typically found in your application metadata.)
Metadata Source
Attributes Required (Please indicate what information will be required by your application)

**Comment by IanW23** [comment]
### **requires Dr. Chida approval and submission**

**Comment by pranav-logan** [comment]
Due to the following:
* Requests for new services/applications to be protected by Single Sign On being restricted only to Faculty.
* The presence of other more important issues. 

SSO integration is currently not being considered.
